### ISSUE TITLE
On Unraid Thread_Limit doesnt seem to affect resource usage.

### ISSUE THREAD

**Issue by DalaraAFL** [TheWicklowWolf/LidaTube#30] opened 2024-09-01 03:55 UTC
Hey, i have thread limit set to 16 on unraid, however it never seems to use more than 1 cpu core. I dont have any cpu pinning or isolation setup for the docker container. 
Im using the docker container under thewicklowwolf/lidatube:latest.

This isnt a major issue for me tbh, just slows things down, so im going to have to run it a bit longer. 

The tools amazing, and thanks for your work!

**Comment by TheWicklowWolf** [comment] 2024-09-02 13:27
> Hey, i have thread limit set to 16 on unraid, however it never seems to use more than 1 cpu core. I dont have any cpu pinning or isolation setup for the docker container. Im using the docker container under thewicklowwolf/lidatube:latest.
> 
> This isnt a major issue for me tbh, just slows things down, so im going to have to run it a bit longer.
> 
> The tools amazing, and thanks for your work!



Are you sure you're using the correct environment variable? You should be able to see in the logs if multiple actions are happening simultaneously.

Also, keep in mind that it runs multithreaded, not multiprocess, so it will only use a single CPU core.

It could also be related to how it's set up on Unraid, but since I'm not running, I can't say.

**Comment by DalaraAFL** [comment] 2024-09-03 14:32
Hey, I didnt realize in python multi threading is locked to a single core (unless you go through converting to multiprocessing). 

to be honest im not entirely sure i understand the point of multi threading a cpu bound application, if it is still stuck to the single cpu core... usually when theres an environment variable to turn up thread count it is to take advantage of multiple cpu cores.

Thanks for the response, it would be nice for this to support full multi threading, but it sounds like that would be a more significant time investment than just fixing a bug :p

**Comment by TheWicklowWolf** [comment] 2024-09-03 16:43
This isn’t a CPU-bound application, so multithreading is highly effective and makes perfect sense in this context.
Additionally, even with multithreading, the system can still be worked quite hard due to the nature of the tasks involved.

Given this, the issue you’re encountering is more likely related to your Unraid setup or a configuration setting within your environment, rather than being a problem with the application itself. 

I’ll close this issue for now since it’s not a bug.

**Closed by TheWicklowWolf** 2024-09-03 16:43 UTC
